=== danielsevillasn/EjerciciosDAM/XML/XSD/Ejercicios XSD/Ejercicio4/Ejercicio4.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movil" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="pantalla">
                                <xs:complexType>
                                    <xs:attribute name="pulgadas" type="xs:float"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="almacenamiento" type="xs:string"/>
                            <xs:element name="precio">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="moneda" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== danielsevillasn/EjerciciosDAM/XML/XSD/Ejercicios XSD/Ejercicio4/Ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://w3.org"
    xsi:noNamespaceSchemaLocation="Ejercicio4.xsd">
    <movil>
        <marca>Samsung</marca>
        <modelo>Galaxy S23</modelo>
        <pantalla pulgadas="6.1" />
        <almacenamiento>128GB</almacenamiento>
        <precio moneda="EUR">850.00</precio>
    </movil>
    <movil>
        <marca>Apple</marca>
        <modelo>iPhone 15 Pro</modelo>
        <pantalla pulgadas="6.7" />
        <almacenamiento>512GB</almacenamiento>
        <precio moneda="EUR">1200.50</precio>
    </movil>
</catalogo>
