=== danielsevillasn/EjerciciosDAM/XML/XSD/Ejercicios XSD/Ejercicio3/Ejercicio3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="videoclub">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="director" type="xs:string" />
                            <!--El
                            tipo gYear obliga a introducir un año en especifico YYYY-->
                            <xs:element name="año" type="xs:gYear" />
                            <xs:element name="genero" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="alquilada" minOccurs="0">
                                <xs:complexType>
                                    <!--El
                                    tipo date obliga a poner año-mes-dia-->
                                    <xs:attribute name="fecha_devolucion" type="xs:date" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <!--Que
                        sea de uso required significa que es obligatorio-->
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <!--Este
                                    pattern nos ayuda a que a la hora de poner el id de una pelicula
                                    este restringido a ser de una manera específica-->
                                    <!--Ha
                                    de empezar por una letra P y seguir con 3 numeros del 0-9-->
                                    <xs:pattern value="P[0-9]{3}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== danielsevillasn/EjerciciosDAM/XML/XSD/Ejercicios XSD/Ejercicio3/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<videoclub xmlns:xsi="http://w3.org"
    xsi:noNamespaceSchemaLocation="Ejercicio3.xsd">
    <pelicula id="P101">
        <titulo>Inception</titulo>
        <director>Christopher Nolan</director>
        <año>2010</año>
        <genero>Ciencia Ficción</genero>
        <genero>Thriller</genero>
        <alquilada fecha_devolucion="2024-05-15" />
    </pelicula>
    <pelicula id="P102">
        <titulo>Toy Story</titulo>
        <director>John Lasseter</director>
        <año>1995</año>
        <genero>Animación</genero>
        <!-- Esta no tiene el elemento alquilada (es opcional) -->
    </pelicula>
</videoclub>
