=== danielsevillasn/EjerciciosDAM/XML/Ejercicios_DTD_2/Ejercicio3/Ejercicio3.dtd
<!ELEMENT supermercado (articulo+)>

<!ATTLIST articulo id ID #REQUIRED>

<!ELEMENT articulo (descripcion,marca?,medida,seccion, oferta*,perecedero?)>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT medida (#PCDATA)>
<!ATTLIST medida unidad CDATA #IMPLIED>
<!ELEMENT seccion (#PCDATA)>
<!ELEMENT oferta (#PCDATA)>
<!ELEMENT perecedero (caducidad | fabricacion)>
<!ELEMENT caducidad (#PCDATA)>
<!ELEMENT fabricacion (#PCDATA)>

=== danielsevillasn/EjerciciosDAM/XML/Ejercicios_DTD_2/Ejercicio3/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE supermercado SYSTEM "Ejercicio3.dtd">
<supermercado>
    <articulo id="articulo1">
        <descripcion>Leche desntada</descripcion>
        <marca>Pascual</marca>
        <medida unidad="SI">1 L</medida>
        <seccion>Leche y Batidos</seccion>
    </articulo>
    <articulo id="articulo2">
        <descripcion>Leche entera</descripcion>
        <marca>Puleva</marca>
        <medida>1,5 L</medida>
        <seccion>Leche y Batidos</seccion>
        <oferta>Lote descuento</oferta>
        <oferta>Dos por uno</oferta>
        <perecedero>
            <fabricacion>Enero2010</fabricacion>
        </perecedero>
    </articulo>
    <articulo id="articulo3">
        <descripcion>Tomate</descripcion>
        <medida unidad="SI">1 Kg</medida>
        <seccion>Frutas y verduras</seccion>
        <perecedero>
            <caducidad>Febrero2010</caducidad>
        </perecedero>
    </articulo>
</supermercado>
