=== danielsevillasn/EjerciciosDAM/XML/DTD/EjerciciosIntroduccionDTD/catalogo.dtd
<!-- Elemento raíz -->
<!ELEMENT catalogo (producto+)>

<!-- Cada producto tiene: nombreProducto, descripcion, precio y caracteristicas -->
<!ELEMENT producto (nombreProducto, descripcion,precio,caracteristicas)>
<!ATTLIST producto id CDATA #REQUIRED>

<!-- Elementos de texto -->
<!ELEMENT nombreProducto (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!-- Precio con texto y un atributo moneda -->
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>

<!-- Conjunto de características -->
<!ELEMENT caracteristicas (caracteristica+)>

<!-- Cada caracteristica está vacía y se define solo con atributos -->
<!ELEMENT caracteristica EMPTY>
<!ATTLIST caracteristica
          tipo CDATA #REQUIRED
          valor CDATA #REQUIRED>

=== danielsevillasn/EjerciciosDAM/XML/ejerciciosxmldtd/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">

<catalogo>
    <producto id="1">
        <nombreProducto>Portátil Lenovo IdeaPad</nombreProducto>
        <descripcion>Portátil de 15 pulgadas con procesador Intel i5</descripcion>
        <precio moneda="EUR">699.99</precio>

        <caracteristicas>
            <caracteristica tipo="Batería" valor="8 horas"/>
            <caracteristica tipo="RAM" valor="16 GB"/>
            <caracteristica tipo="Almacenamiento" valor="512 GB SSD"/>
        </caracteristicas>
    </producto>

    <producto id="2">
        <nombreProducto>Smartphone Samsung Galaxy</nombreProducto>
        <descripcion>Pantalla AMOLED de 6.5 pulgadas</descripcion>
        <precio moneda="EUR">499.50</precio>

        <caracteristicas>
            <caracteristica tipo="Cámara" valor="64 MP"/>
            <caracteristica tipo="Batería" valor="5000 mAh"/>
            <caracteristica tipo="Conectividad" valor="5G"/>
        </caracteristicas>
    </producto>
</catalogo>
