=== danielsevillasn/EjerciciosDAM/XML/EJERCICIOS_XML_DTD/Ejercicio1.dtd
<!ELEMENT matricula (ciclo, alumnos)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, año, módulos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT módulos (módulo+)>
<!ELEMENT módulo (#PCDATA)>

=== danielsevillasn/EjerciciosDAM/XML/DTD/EJERCICIOS_XML_DTD/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "Ejercicio1.dtd">
<matricula>
    <ciclo>Administración de sistemas informáticos y redes</ciclo>
    <alumnos>
        <alumno>
            <nombre>Federico Pérez</nombre>
            <año>2010</año>
            <módulos>
                <módulo>XML</módulo>
                <módulo>Redes Locales</módulo>
            </módulos>
        </alumno>
    </alumnos>
</matricula>
