=== danielsevillasn/EjerciciosDAM/XML/XSD/Ejercicios XSD/Ejercicio1/Ejercicio1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="CICLO">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MODULO" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DENOMINACION" type="xs:string" />
                            <xs:element name="SIGLAS">
                                <xs:simpleType>
                                    <!--Restriccion
                                    que obliga a minimo poner un string de 2 caracteres y como
                                    máximo 5-->
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="2" />
                                        <xs:maxLength value="5" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--Elemento
                            tipo string que puede aparecer más de una vez-->
                            <xs:element name="PROFESOR" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="DESCRIPCION" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== danielsevillasn/EjerciciosDAM/XML/XSD/Ejercicios XSD/Ejercicio1/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<CICLO xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio1.xsd">
    <MODULO>
        <DENOMINACION>Sistemas Informáticos</DENOMINACION>
        <SIGLAS>SI</SIGLAS>
        <PROFESOR>María López</PROFESOR>
        <DESCRIPCION>Hardware, sistemas operativos y redes
            básicas</DESCRIPCION>
    </MODULO>
    <MODULO>
        <DENOMINACION>Aplicaciones Informaticas</DENOMINACION>
        <SIGLAS>AI</SIGLAS>
        <PROFESOR>MARTA GÓMEZ</PROFESOR>
        <PROFESOR>Enrique barrios</PROFESOR>
        <DESCRIPCION>Asignatura cuatrimestral</DESCRIPCION>
    </MODULO>
</CICLO>
